from django.core.management.base import NoArgsCommand
from importer.parsers.event import EventAdapter
from importer.consumer import ScrapeFeedConsumer

class Command(NoArgsCommand):
    help = 'Loads scraped object generated by scrapy'

    def handle_noargs(self, **options):
        consumer = ScrapeFeedConsumer()
        parser = EventAdapter()
        for event in consumer.events():
            parser.parse(event)
