from django.core.management.base import NoArgsCommand
from importer.parsers.event import EventParser
from importer.consumer import ScrapeFeedConsumer

class Command(NoArgsCommand):
    help = 'Loads scraped object generated by scrapy'

    def handle(self, **options):
        consumer = ScrapeFeedConsumer()
        parser = EventParser()
        for event in consumer.events():
            parser.parse(event)
